# Generated by Django 2.0 on 2018-12-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='coin',
            field=models.CharField(blank=True, max_length=33, null=True, verbose_name='coin'),
        ),
        migrations.AlterField(
            model_name='market',
            name='currency',
            field=models.CharField(blank=True, max_length=33, null=True, verbose_name='currency'),
        ),
    ]
