# Generated by Django 2.0.9 on 2018-12-04 22:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import member.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='登录名')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('commission_type', models.IntegerField(choices=[(0, '按买入币种比例')], default=0, verbose_name='手续费计费方式')),
                ('commission_rate', models.DecimalField(decimal_places=8, default=0.0001, max_digits=9, verbose_name='手续费比例')),
                ('warning_line', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='告警线')),
                ('close_out_line', models.FloatField(default=0.6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='平仓线')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Account', verbose_name='所属交易账号')),
                ('commission_coin', models.ForeignKey(blank=True, help_text='计费方式为按买入币种比例时，本设置无效。', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CryptoCoin', verbose_name='结算币种')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '交易员',
                'verbose_name_plural': '交易员',
            },
            managers=[
                ('objects', member.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'verbose_name': '交易员',
                'verbose_name_plural': '交易员',
            },
            bases=('member.user',),
            managers=[
                ('objects', member.managers.TraderManager()),
            ],
        ),
    ]
