# Generated by Django 2.0 on 2018-12-09 21:29

from django.db import migrations
import member.managers


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name_plural': '系统管理员',
                'proxy': True,
                'verbose_name': '系统管理员',
                'indexes': [],
            },
            bases=('member.user',),
            managers=[
                ('objects', member.managers.AdminManager()),
            ],
        ),
    ]
