# Generated by Django 2.0.9 on 2018-12-04 15:42

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='使用真实的邮箱或账号名', max_length=100, verbose_name='账号名')),
                ('key', models.CharField(blank=True, max_length=250, null=True, verbose_name='api key')),
                ('secret', models.CharField(blank=True, max_length=250, null=True, verbose_name='api secret')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('can_trade', models.BooleanField(default=True, editable=False, verbose_name='可变易')),
                ('can_withdraw', models.BooleanField(default=True, editable=False, verbose_name='可提现')),
                ('can_deposit', models.BooleanField(default=True, editable=False, verbose_name='可充值')),
                ('maker_commission', models.IntegerField(default=0, editable=False, verbose_name='Maker手续费')),
                ('taker_commission', models.IntegerField(default=0, editable=False, verbose_name='Taker手续费')),
                ('buyer_commission', models.IntegerField(default=0, editable=False, verbose_name='买家手续费')),
                ('seller_commission', models.IntegerField(default=0, editable=False, verbose_name='卖家续费')),
                ('extra_info', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='其他信息')),
                ('laset_sync', models.BigIntegerField(default=0, editable=False, verbose_name='最后同步时间')),
            ],
            options={
                'verbose_name_plural': '交易所账号',
                'verbose_name': '交易所账号',
            },
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.IntegerField(choices=[(0, '帐号转入'), (1, '帐号转出'), (2, '帐号买入'), (3, '帐号买出'), (4, '帐号交易手续费'), (10, '交易员转入'), (11, '交易员转出'), (12, '交易买入'), (13, '交易员卖出'), (14, '平台佣金'), (15, '交易员手续费'), (16, '交易员转帐（转出）'), (17, '交易员转帐（转入）')], verbose_name='类型')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='数量')),
                ('effect_account', models.BooleanField(default=True, editable=False, verbose_name='影响账户资产')),
                ('usdt_value', models.DecimalField(decimal_places=8, default=0, max_digits=19, verbose_name='USDT价值')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发生日期')),
                ('create_time', models.TimeField(auto_now_add=True, verbose_name='发生时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Account', verbose_name='交易所账号')),
            ],
            options={
                'verbose_name_plural': '资产明细',
                'verbose_name': '资产明细',
            },
        ),
        migrations.CreateModel(
            name='CryptoCoin',
            fields=[
                ('coinId', models.CharField(max_length=33, primary_key=True, serialize=False, verbose_name='代号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('website', models.URLField(blank=True, null=True, verbose_name='网站')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '加密货币',
                'verbose_name': '加密货币',
            },
        ),
        migrations.CreateModel(
            name='FrozenAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='数量')),
                ('free', models.BooleanField(default=False, help_text='交易成功返回的', verbose_name='是否解冻')),
                ('manual', models.BooleanField(default=False, verbose_name='是否人工冻结')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Account', verbose_name='交易员账号')),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.CryptoCoin', verbose_name='资产')),
            ],
            options={
                'verbose_name_plural': '冻结资产',
                'verbose_name': '冻结资产',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='使用大写', max_length=50, verbose_name='币对')),
                ('coin_precision', models.IntegerField(default=8, help_text='精确到小数点后8位', verbose_name='交易资产精度')),
                ('currency_precision', models.IntegerField(default=8, help_text='精确到小数点后8位', verbose_name='报价资产精度')),
                ('diaable', models.BooleanField(default=False, verbose_name='禁止交易')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='市场状态')),
                ('order_types', models.CharField(blank=True, max_length=200, null=True, verbose_name='支持交易类型')),
                ('iceberg_allowed', models.BooleanField(default=False, verbose_name='允许冰山交易')),
                ('extra_info', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='其他信息')),
                ('last_checksum', models.CharField(blank=True, help_text='用于检查服务器返回数据是否更新', max_length=100, null=True, verbose_name='信息签名')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CryptoCoin', verbose_name='交易资产')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currencymarket', to='core.CryptoCoin', verbose_name='报价资产')),
            ],
            options={
                'verbose_name_plural': '交易市场',
                'verbose_name': '交易市场',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, verbose_name='交易币对')),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=19, verbose_name='数量')),
                ('time_in_force', models.CharField(choices=[('GTC', 'GTC'), ('IOC', 'IOC'), ('FOK', 'FOK')], default='GTC', max_length=3, verbose_name='有效期')),
                ('price', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='价格')),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=19, null=True, verbose_name='止盈止损价格')),
                ('side', models.CharField(choices=[('SELL', '卖出'), ('BUY', '买入')], default='SELL', max_length=10, verbose_name='方向')),
                ('order_type', models.CharField(choices=[('LIMIT', '限价单'), ('MARKET', '市价单'), ('STOP_LOSS', '止损单'), ('STOP_LOSS_LIMIT', '止损限价单'), ('TAKE_PROFIT', '获利单'), ('TAKE_PROFIT_LIMIT', '获利限价单'), ('LIMIT_MAKER', '限价造市')], default='LIMIT', max_length=30, verbose_name='类型')),
                ('platform_order_id', models.IntegerField(db_index=True, default=-1, verbose_name='平台订单号')),
                ('iceberg_quantity', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=19, null=True, verbose_name='冰山交易量')),
                ('status', models.CharField(choices=[('PREPARE', '准备中'), ('NEW', '新订单'), ('PARTIALLY_FILLED', '部份完成'), ('FILLED', '已完成'), ('PREPARE_CANCEL', '准备取消'), ('CANCELED', '已取消'), ('PENDING_CANCEL', '取消中'), ('REJECTED', '被拒绝'), ('EXPIRED', '超时'), ('DELETED', '已删除')], default='PREPARE', max_length=20, verbose_name='状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('extra_info', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='其他信息')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Account', verbose_name='交易所账号')),
                ('buy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying', to='core.CryptoCoin', verbose_name='买入对象')),
                ('sell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling', to='core.CryptoCoin', verbose_name='卖出对象')),
            ],
            options={
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('slug', models.SlugField(help_text='允许英文，数字及下划线', unique=True, verbose_name='代号')),
                ('website', models.URLField(blank=True, null=True, verbose_name='网站')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='描述')),
                ('last_checksum', models.CharField(blank=True, help_text='用于检查服务器返回数据是否更新', max_length=100, null=True, verbose_name='信息签名')),
                ('commission_rate', models.DecimalField(decimal_places=8, default=0.01, max_digits=9, verbose_name='交易手续费率')),
                ('commission_asset', models.ForeignKey(blank=True, help_text='交易佣金结算币', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CryptoCoin', verbose_name='结算币')),
            ],
            options={
                'verbose_name_plural': '交易所',
                'verbose_name': '交易所',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='价格')),
                ('commission', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='佣金')),
                ('commission_asset', models.CharField(max_length=20, verbose_name='佣金结算货币')),
                ('is_buyer', models.BooleanField(verbose_name='是否买家')),
                ('is_maker', models.BooleanField(default=False, verbose_name='是否造市')),
                ('is_best_match', models.BooleanField(default=True, verbose_name='最佳匹配')),
                ('platform_trade_id', models.IntegerField(default=-1, verbose_name='平台交易号')),
                ('platform_order_id', models.IntegerField(db_index=True, default=-1, verbose_name='平台订单号')),
                ('trade_time', models.BigIntegerField(verbose_name='交易时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('extra_info', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='其他信息')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name_plural': '交易',
                'verbose_name': '交易',
            },
        ),
        migrations.AddField(
            model_name='market',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Platform', verbose_name='交易平台'),
        ),
        migrations.AddField(
            model_name='frozenasset',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Order', verbose_name='所属订单'),
        ),
        migrations.AddField(
            model_name='assetlog',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.CryptoCoin', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='assetlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Order', verbose_name='所属订单'),
        ),
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Platform', verbose_name='交易所'),
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('platform', 'symbol')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('platform', 'name')},
        ),
    ]
